apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: lanchonete
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://productrds.c56iugywe6gv.us-east-1.rds.amazonaws.com:3306?useTimezone=true&serverTimezone=America/Sao_Paulo
  SPRING_DATASOURCE_USERNAME: root
  environment: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: lanchonete
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=