apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: lanchonete
  labels:
    app: product
    environment: production
spec:
  type: ClusterIP  # Alterado de LoadBalancer para ClusterIP
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
